### ISSUE TITLE
multi axe Y

### ISSUE THREAD

**Issue by amaussa** [smouksassi/ggquickeda#10]
Samer MOUKSASSI <samermouksassi@gmail.com> give me your name.
But I would like to make some change and for this moment without success.

Is it possible for you to help me ?

I would like by priority :

- possibility to add  and show multi axe Y

see my sample file with modification

p <- ggplot(plotdata, aes_string(x=input$x, y=input$y)) 
       # p <- p + aes_string(y=input$y2) # add this line provide a error ?

- possiblity to import csv and skip the header lenghtvalue  defini by a box when you import the cvs

-add  panel to show the header 
 

do you thinks it's possible for you to help me.

Thanks in advanced

Alain

**Comment by smouksassi** [comment]
It is possible to select multiple y and it will facet automatically. Please add a reproducible csv or dataset

**Comment by amaussa** [comment]
HI good new after to check the last version.
but I have some requests:
- possibility to skip the header (add in the box the number of line)
- possibility to save the setup , by import csv reload a configuration and not redo all manually
- possibility to show by range value ( I don't find) ex 1 to 500
- possibility to show many Y in the same graph ? temp + humidity
see pictures
![Capture](https://user-images.githubusercontent.com/32430515/67564105-82fbce80-f722-11e9-926d-b3b6e4a3785d.PNG)

**Comment by smouksassi** [comment]
Without data hard to help but here is some replies please open separate issue by feature

**Possibility to save the setup , by import csv reload a configuration and not redo all manually:**
currently, there is no development bandwidth to do this PR's welcome but ggquickeda is complex enough and this will need a significant re-write to large protions I doubt it will ever happen.

**Possibility to show by range value ( I don't find) ex 1 to 500**
the apps support filtering and custom x/ axis zooms  please explain more

**possibility to show many Y in the same graph? temp + humidity**
this is bad practice especially for variables that have completely independent scales the facet is in line with best practices and ggplot philosophy.
you can do the two variables in the same panel grouping by yvars and maybe coloring by it but both will share the same axis. ( no support for dup axis which is not useful unless variable y2 is a function of variable y 1.

**Possibility to skip the header (add in the box the number of line)**
I need the data or that you provide more info how many lines your header is are the separtors and na codes fine ?

**Comment by amaussa** [comment]
thanks very good jobs
I'm going to open separate issues
Alain

**Comment by smouksassi** [comment]
Close in favor of separate filed issues
