### ISSUE TITLE
skip header

### ISSUE THREAD

**Issue by amaussa** [smouksassi/ggquickeda#11]
Possibility to skip the header (add in the box the number of line)
the length dependency of the .CSV file to import.
could be nice to add a additional box to enter a number to skip to suppress the header.
Thanks
Alain

**Comment by amaussa** [comment]
add temporary solution:
server.R
# Load user data
  observeEvent(input$datafile, {
    file <- input$datafile$datapath
    values$maindata <- read.csv(file, skip=input$headerdigits, na.strings = c("NA","."))
    #values$maindata <- read.csv(file,na.strings = c("NA","."))
  })
UIR file :
,
          
          uiOutput("headervar"),
          numericInput("headerdigits",label = "header line number",value = 1,min=1,max=20),
         
          br(),

**Comment by smouksassi** [comment]
For the moment I only support limited input file i.e just CSV and with simple header feel free to modify the package for your own needs there are some shiny apps out there that have a complete UI around importing files. Closing as it is not on the roadmap to extend the import files functionality for now.
