### ISSUE TITLE
control the color of the variable

### ISSUE THREAD

**Issue by amaussa** [smouksassi/ggquickeda#13]
I don't find in the doc and inside this interface how to change the color by Y variable ?
if you have a solution
Thanks

**Comment by smouksassi** [comment]
Have you tried color by yvars ? I need more info

**Comment by amaussa** [comment]
yes I don't know how to proceed. if you have some sample. thx
I hace slect multi Y variable and I would like to assign differents color.

**Comment by smouksassi** [comment]
In the menu for color input can't you select yvars?

**Comment by amaussa** [comment]
I'll try thx

**Comment by amaussa** [comment]
work weel, I have a lot of variable Y and I don't scroll on the end. is my fault
That NICE, congratulation this interface is sufficient to cover many different type of file
Alain

**Comment by smouksassi** [comment]
Thank you please close the issue if this is what you needed.
