### ISSUE TITLE
date & time in the header

### ISSUE THREAD

**Issue by amaussa** [smouksassi/ggquickeda#14]
Date & Time
5/24/2019 9:49
possibility to filter some X or Y to assign the correct date & time format to be able to use it .
could be nice

**Comment by smouksassi** [comment]
I need an example csv and description of what you want to do

**Comment by amaussa** [comment]
the file have more 20000 line
ex sample line below.
I would like to see Date & Time in the X and  proble, current, .. in Y
work well with NO. but with Date & Time I don't see the value
No:	 Date & Time	 DUT Mode	 Probe of Humidity(%)	 Probe of Temperature(°C)	 Voltage_reference(V)	Voltage Level [V]	Time	 Current [A]	 Power [W]
1	5/24/2019 9:49	Sleep Mode	7.2	24.8	14	14	5/24/2019 9:49	0.0002	0.0028
2	5/24/2019 9:50	Sleep Mode	3.9	25.8	14	14	5/24/2019 9:50	0.000199	0.002786
3	5/24/2019 9:51	Sleep Mode	2.7	26.3	14	14	5/24/2019 9:51	0.000197	0.002758
4	5/24/2019 9:52	Sleep Mode	2.2	26.5	14	14	5/24/2019 9:52	0.000195	0.00273
5	5/24/2019 9:53	Sleep Mode	1.7	26.5	14	14	5/24/2019 9:53	0.000197	0.002758
6	5/24/2019 9:54	Sleep Mode	1.5	26.5	14	14	5/24/2019 9:54	0.000195	0.00273
7	5/24/2019 9:55	Sleep Mode	1.3	26.4	14	14	5/24/2019 9:55	0.000196	0.002744
8	5/24/2019 9:56	Sleep Mode	1.3	26.5	14	14	5/24/2019 9:56	0.000194	0.002716
9	5/24/2019 9:57	Sleep Mode	1.2	26.5	14	14	5/24/2019 9:57	0.000194	0.002716

**Comment by smouksassi** [comment]
please provide a file or a command that I can build your data in R. currently you cannot do filters or modify scales and format  for date-time just plotting works
```r
exampledata <- data.frame (
            voltage= c(1:5,6:2),
            datetime = as.POSIXct( paste0("05/24/2019 9:4",0:9) ,
                                   format="%m/%d/%Y %H:%M")
            )

ggquickeda::run_ggquickeda(exampledata)

```
what do you exactly need ?

**Comment by amaussa** [comment]
yes thx
