### ISSUE TITLE
Why not continue to use the ‘Data Mappings panel’?

### ISSUE THREAD

**Issue by s0521** [smouksassi/ggquickeda#15]
I think the ‘Data Mappings panel’ in Phoenix software is very helpful to set up, very easy to operate, ten thousand times better than the drop-down menu, or drag and drop!
Why don't you continue to use this style?

The current interface operations are not friendly at all. Frequent mouse clicks are very cumbersome and inefficient. 

I thik the biggest function of the graphical interface is to help users intuitively, quickly, and simply complete the fixed mode tasks.

**Comment by smouksassi** [comment]
Dear S0521, this repo and package is not related to the Phoenix software. The Phoenix dev chose to incorporate ggquickeda in their distribution but I am not aware of an open API for full integration into the Phoenix mapping etc. Please email Certara support and submit an issue about how you need plotting to work. Pro developers can always fork and make ggquickeda better before integrating into a full pro software.
