### ISSUE TITLE
How to build a correlation matrix using the tool

### ISSUE THREAD

**Issue by solmazeradat** [smouksassi/ggquickeda#22]
Hi. Thank you @smouksassi  for the great demo of the tool thins morning. Had  quick play around with the tool and was wandering can the tool produce a correlation matrix of the data, similar to the following examples [https://www.r-graph-gallery.com/correlogram.html](url). Thank you.

**Comment by smouksassi** [comment]
Hi you can do that by choosing the list of your y variables to remove any x variable and then click on the pairs plot you can then choose to show correlation on say upper and a smooth or density on the lower part of the triangle also seehow you can mix with categorical and color by a covariate of interest:

![correlationexample](https://user-images.githubusercontent.com/5131281/107032548-ada95380-67bc-11eb-9880-c9f4f7f702e8.png)

**Comment by solmazeradat** [comment]
That's great @smouksassi. thank for all your help. I created some correlation graphs using the application. 

![image](https://user-images.githubusercontent.com/11243960/107058776-ef41fa80-67cc-11eb-9025-f2bac0b72814.png)

Under **Pairs Plot Options** I could not see the correlation option as you had highlighted in your screen shot.  Many thank Solmaz

**Comment by smouksassi** [comment]
Please use the github version
The one on cran will not let you change the default upper correlation for continuous versus continuous
