### ISSUE TITLE
Suggest removing dependency on ggstance

### ISSUE THREAD

**Issue by billdenney** [smouksassi/ggquickeda#25]
Thanks for the helpful package!

The `ggstance` package indicates that it has been superseded by features of `ggplot2`, itself (https://cran.r-project.org/web/packages/ggstance/index.html).  I think it would be helpful to remove the dependency since the package is not likely to be maintained.

**Comment by smouksassi** [comment]
yes now that the key of legends are also auto-rotating and we have all the positions working
 I can remove dependence on ggstance
 thanks for your kind words about the package and for  the issue will keep it open till the next release
