### ISSUE TITLE
Should LICENSE file say "copyright Samer Mouksassi" or "copyright Certara"?

### ISSUE THREAD

**Issue by daattali** [smouksassi/ggquickeda#3]

**Comment by daattali** [comment]
@smouksassi let me know

**Comment by smouksassi** [comment]
closing this for now

**Comment by daattali** [comment]
License currently says your name

**Comment by smouksassi** [comment]
ok will leave it open to track as we have multiple contributors and need to figure this out

**Comment by daattali** [comment]
You're the main person, there's no problem having your name. The main
question is whether you want it to have your name or Certara

**Comment by smouksassi** [comment]
ok to have it as my Name pending some discussion with other parties let us keep this open for now

**Comment by smouksassi** [comment]
closing as it is fine as is
