### ISSUE TITLE
Deal with non-CRAN dependencies `ggkm`

### ISSUE THREAD

**Issue by daattali** [smouksassi/ggquickeda#4]
Currently both ggkm and table1 are only offered as github packages, so they are mentioned in the `DESCRIPITON` file as remote packages. This is fine for now but it means that `ggquickeda` can only be installed as a github package, not on CRAN. To get to CRAN, all dependencies must be on CRAN.

**Comment by smouksassi** [comment]
@sachsmc would you like to make a PR to push the ggkm part into the repo ?

**Comment by smouksassi** [comment]
@benjaminrich do you plan to publish table1 into CRAN anytime soon ? Alternatively we can include the relevant part into ggquickeda

**Comment by daattali** [comment]
@sachsmc said we can include the ggkm code in a separate file within the app

**Comment by daattali** [comment]
@smouksassi I've added both ggkm and table1 code into the package source code. If table1 ever gets on CRAN we can revisit. Can we close this issue or do we want to wait for table1 to be on CRAN?

**Comment by smouksassi** [comment]
now that table1 is on CRAN we need to use the funnctios from table1 and deprecate the one from ggquickeda for the html tables.  as for ggkm it will stay part of ggquickeda as per @sachsmc preference.

**Comment by daattali** [comment]
dependency on table1 has been removed

**Comment by daattali** [comment]
If there's no plan on ever putting ggkm on CRAN, this issue can be closed
