### ISSUE TITLE
Kill the application when a browser tab closes?

### ISSUE THREAD

**Issue by daattali** [smouksassi/ggquickeda#6]
@smouksassi need to decide whether we want to kill the app when a browser is closed.

We can make it so that only when the app is launched using the `run_ggquickeda()` function, it will die when a browser window is closed. However this will mean that opening the app is multiple windows will kill all sessions when a single tab is closed.

**Comment by smouksassi** [comment]
Let us think about it a little bit more how do you launch multiple run_ggquickeda() say we open multiple rsessions, or rstudio projects and we lauch an app from each: run_ggquickeda() will killing one window also kill the app launched from the separate R session this might not be what we want

**Comment by daattali** [comment]
If you open two r sessions and launch it from each one then killing one
will not affect the other

**Comment by smouksassi** [comment]
ok then it is fine because I don't see how we can open multiple version of the app in separate browser windows from one single R session since when we open one it keeps R busy
