### ISSUE TITLE
faceting issue due to the new ggplot3.0.0 update

### ISSUE THREAD

**Issue by smouksassi** [smouksassi/ggquickeda#7]
with new ggplot when facting by colum and extra column  the faceting will not work as ggplot will try to evaluate the addition of say RACE + SEX  and it will generate an NA.

We might have to support both versions / interface for people that did not update ggplot to the latest releaese

**Comment by daattali** [comment]
From email:

Bug apparent when we facet by more than one column. See below the new ggplot try to literraly add  the two variables as opoposed to treating it as formula

![image](https://user-images.githubusercontent.com/952340/44942618-0b334d80-ad84-11e8-9b6a-7fd44cff104a.png)

**Comment by daattali** [comment]
Great, you've done my job for me :)
